CREATE TABLE customer(
custNo VARCHAR(8) NOT NULL,
custName VARCHAR(256) NOT NULL,
address VARCHAR(256) NOT NULL,
internal CHAR(1) NOT NULL,
contact VARCHAR(256) NOT NULL,
phone VARCHAR(256) NOT NULL,
city VARCHAR(256) NOT NULL,
state VARCHAR(256) NOT NULL,
zip VARCHAR(10) NOT NULL,
CONSTRAINT PK_CUSTOMER PRIMARY KEY(custNo)
);